import { Amiri, Bebas_Neue, JetBrains_Mono, Smooch_Sans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const Smooch = Smooch_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-smooch",
});

const Bebas = Bebas_Neue({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
	variable: "--font-bebas",
});

const JetBrains = JetBrains_Mono({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-jetbrains",
});

const Amire = Amiri({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-amiri",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${Smooch.variable} ${Bebas.variable} ${JetBrains.variable} ${Amire.variable}`}>
			{children}
		</html>
	);
}
